[package]
name = "arceos-net-module-test"
version = "0.1.0"
edition.workspace = true
authors = ["PingGuoMiaoMiao <student@example.com>"]

[dependencies]
axstd = { workspace = true, features = ["alloc", "net"], optional = true }