# 自定义 QEMU virt 平台配置

# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "myqemu"
# Stack size of each task.
task-stack-size = 0x40000
# Number of timer ticks per second (Hz).
ticks-per-sec = 100

[devices]
# UART Address
uart-paddr = 0x0900_0000
# UART IRQ number
uart-irq = 33
# Timer interrupt num (PPI, physical timer).
timer-irq = 30

[plat]
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000
# Number of CPUs.
cpu-num = 1
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000
# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000