# Configuration for myqemu custom platform

arch = "aarch64"
platform = "myqemu"
package = "axplat-myqemu"
log-level = "info"
# Stack size of each task.
task-stack-size = 0x40000
# Number of timer ticks per second (Hz).
ticks-per-sec = 100

[plat]
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000
# Number of CPUs.
cpu-num = 1
# Kernel address space base.
kernel-aspace-base = "0xffff_0000_0000_0000"
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000"
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_4020_0000"
# Offset of bus address and phys address.
phys-bus-offset = 0
# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000
# Linear mapping offset.
phys-virt-offset = "0xffff_0000_0000_0000"

[devices]
# Timer interrupt num.
timer-irq = 30              # uint
# IPI interrupt num
ipi-irq = 1                 # uint
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0           # uint
# End PCI bus number.
pci-bus-end = 0             # uint
# PCI device memory ranges.
pci-ranges = []             # [(uint, uint)]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [
    [0x0900_0000, 0x1000]  # UART
]